# Stage 1: Build stage
FROM rust:1.79-slim

# Install cargo-build-deps for better dependency caching
RUN cargo install cargo-build-deps

# Create a new Rust binary project to leverage dependency caching
RUN cd /tmp && USER=root cargo new --bin rust-app
WORKDIR /tmp/rust-app

# Install necessary build tools and dependencies
RUN apt-get update && \
    apt-get install -y build-essential pkg-config libssl-dev && \
    rm -rf /var/lib/apt/lists/*


# Copy the Cargo.toml and Cargo.lock files to the container
COPY Cargo.toml Cargo.lock ./

# Build only the dependencies to cache them
RUN cargo build-deps --release

# Copy the source code to the container
COPY src /tmp/rust-app/src

# Build the application
RUN cargo build --release

CMD [ "./tmp/rust-app/target/release/rust-app" ]