apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-deployment
  namespace: todo
  labels:
    app: rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust
  template:
    metadata:
      labels:
        app: rust
    spec:
      containers:
      - name: rust
        image: shubhamshinde2206/rust:10123519720
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: rust-service
spec:
  type: ClusterIP 
  selector:
    app: rust
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000